// lib/jobs.js
const jobs = [
  // Job 1
  {
    name: 'Finance',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Finance',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/finance',
    submit_URL: '#',
  },
  // Job 2
  {
    name: 'Human Resource',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Human Capital & Talent Acquisition',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/human-resource',
    submit_URL: '#',
  },
  // Job 3
  {
    name: 'Web Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/web-developer',
    submit_URL: '#',
  },
  // Job 4
  {
    name: 'Copywritting',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing & Content Writer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/copywriting',
    submit_URL: '#',
  },
  // Job 5
  {
    name: 'Personal Assistant',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Personal Assistant',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/personal-assistant',
    submit_URL: '#',
  },
  // Job 6
  {
    name: 'Affiliate',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Ads, Affiliate & Social Media',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/affiliate',
    submit_URL: '#',
  },
  // Job 7
  {
    name: 'CRM',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'CRM',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/crm',
    submit_URL: '#',
  },
  // Job 8
  {
    name: 'Purchasing',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Purchasing',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: 'career/purchasing',
    submit_URL: '#',
  },
  // Job 9
  {
    name: 'Grapich Designer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Design & UX',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 10
  {
    name: 'Ads Facebook',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 1
  {
    name: 'Backend Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/finance',
    submit_URL: '#',
  },
  // Job 2
  {
    name: 'Recruiter',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Human Capital & Talent Acquisition',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/human-resource',
    submit_URL: '#',
  },
  // Job 3
  {
    name: 'Front End Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/web-developer',
    submit_URL: '#',
  },
  // Job 4
  {
    name: 'Penulis Artikel',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing & Content Writer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/copywriting',
    submit_URL: '#',
  },
  // Job 5
  {
    name: 'Pemesan Tiket Pesawat',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Personal Assistant',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/personal-assistant',
    submit_URL: '#',
  },
  // Job 6
  {
    name: 'Tukang Email',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Ads, Affiliate & Social Media',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/affiliate',
    submit_URL: '#',
  },
  // Job 7
  {
    name: 'Hobi Ngobrol',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'CRM',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/crm',
    submit_URL: '#',
  },
  // Job 8
  {
    name: 'Tukang Nawar',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Purchasing',
    location: 'PIK, The New Jakarta City',
    availability: 2,
    URL: 'career/purchasing',
    submit_URL: '#',
  },
  // Job 9
  {
    name: 'Lembur sehari hari',
    time: 'Fulltime',
    staff_level: 'Pengganti Kak Ian',
    division: 'Design & UX',
    location: 'Abu Dhabi, UAE',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 10
  {
    name: 'tukang bangunan digital',
    time: 'Fulltime',
    staff_level: 'CEO',
    division: 'Design & UX',
    location: 'California, America',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 1
  {
    name: 'Finance',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Finance',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/finance',
    submit_URL: '#',
  },
  // Job 2
  {
    name: 'Human Resource',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Human Capital & Talent Acquisition',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/human-resource',
    submit_URL: '#',
  },
  // Job 3
  {
    name: 'Web Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/web-developer',
    submit_URL: '#',
  },
  // Job 4
  {
    name: 'Copywritting',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing & Content Writer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/copywriting',
    submit_URL: '#',
  },
  // Job 5
  {
    name: 'Personal Assistant',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Personal Assistant',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/personal-assistant',
    submit_URL: '#',
  },
  // Job 6
  {
    name: 'Affiliate',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Ads, Affiliate & Social Media',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/affiliate',
    submit_URL: '#',
  },
  // Job 7
  {
    name: 'CRM',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'CRM',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/crm',
    submit_URL: '#',
  },
  // Job 8
  {
    name: 'Purchasing',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Purchasing',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: 'career/purchasing',
    submit_URL: '#',
  },
  // Job 9
  {
    name: 'Grapich Designer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Design & UX',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 10
  {
    name: 'Ads Facebook',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 1
  {
    name: 'Backend Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/finance',
    submit_URL: '#',
  },
  // Job 2
  {
    name: 'Recruiter',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Human Capital & Talent Acquisition',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/human-resource',
    submit_URL: '#',
  },
  // Job 3
  {
    name: 'Front End Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/web-developer',
    submit_URL: '#',
  },
  // Job 4
  {
    name: 'Penulis Artikel',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing & Content Writer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/copywriting',
    submit_URL: '#',
  },
  // Job 5
  {
    name: 'Pemesan Tiket Pesawat',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Personal Assistant',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/personal-assistant',
    submit_URL: '#',
  },
  // Job 6
  {
    name: 'Tukang Email',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Ads, Affiliate & Social Media',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/affiliate',
    submit_URL: '#',
  },
  // Job 7
  {
    name: 'Hobi Ngobrol',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'CRM',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/crm',
    submit_URL: '#',
  },
  // Job 8
  {
    name: 'Tukang Nawar',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Purchasing',
    location: 'PIK, The New Jakarta City',
    availability: 2,
    URL: 'career/purchasing',
    submit_URL: '#',
  },
  // Job 9
  {
    name: 'Lembur sehari hari',
    time: 'Fulltime',
    staff_level: 'Pengganti Kak Ian',
    division: 'Design & UX',
    location: 'Abu Dhabi, UAE',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 10
  {
    name: 'tukang bangunan digital',
    time: 'Fulltime',
    staff_level: 'CEO',
    division: 'Design & UX',
    location: 'California, America',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 1
  {
    name: 'Finance',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Finance',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/finance',
    submit_URL: '#',
  },
  // Job 2
  {
    name: 'Human Resource',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Human Capital & Talent Acquisition',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/human-resource',
    submit_URL: '#',
  },
  // Job 3
  {
    name: 'Web Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/web-developer',
    submit_URL: '#',
  },
  // Job 4
  {
    name: 'Copywritting',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing & Content Writer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/copywriting',
    submit_URL: '#',
  },
  // Job 5
  {
    name: 'Personal Assistant',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Personal Assistant',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/personal-assistant',
    submit_URL: '#',
  },
  // Job 6
  {
    name: 'Affiliate',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Ads, Affiliate & Social Media',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/affiliate',
    submit_URL: '#',
  },
  // Job 7
  {
    name: 'CRM',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'CRM',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/crm',
    submit_URL: '#',
  },
  // Job 8
  {
    name: 'Purchasing',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Purchasing',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: 'career/purchasing',
    submit_URL: '#',
  },
  // Job 9
  {
    name: 'Grapich Designer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Design & UX',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 10
  {
    name: 'Ads Facebook',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 1
  {
    name: 'Backend Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/finance',
    submit_URL: '#',
  },
  // Job 2
  {
    name: 'Recruiter',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Human Capital & Talent Acquisition',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/human-resource',
    submit_URL: '#',
  },
  // Job 3
  {
    name: 'Front End Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/web-developer',
    submit_URL: '#',
  },
  // Job 4
  {
    name: 'Penulis Artikel',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing & Content Writer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/copywriting',
    submit_URL: '#',
  },
  // Job 5
  {
    name: 'Pemesan Tiket Pesawat',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Personal Assistant',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/personal-assistant',
    submit_URL: '#',
  },
  // Job 6
  {
    name: 'Tukang Email',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Ads, Affiliate & Social Media',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/affiliate',
    submit_URL: '#',
  },
  // Job 7
  {
    name: 'Hobi Ngobrol',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'CRM',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/crm',
    submit_URL: '#',
  },
  // Job 8
  {
    name: 'Tukang Nawar',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Purchasing',
    location: 'PIK, The New Jakarta City',
    availability: 2,
    URL: 'career/purchasing',
    submit_URL: '#',
  },
  // Job 9
  {
    name: 'Lembur sehari hari',
    time: 'Fulltime',
    staff_level: 'Pengganti Kak Ian',
    division: 'Design & UX',
    location: 'Abu Dhabi, UAE',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 10
  {
    name: 'tukang bangunan digital',
    time: 'Fulltime',
    staff_level: 'CEO',
    division: 'Design & UX',
    location: 'California, America',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 1
  {
    name: 'Finance',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Finance',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/finance',
    submit_URL: '#',
  },
  // Job 2
  {
    name: 'Human Resource',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Human Capital & Talent Acquisition',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/human-resource',
    submit_URL: '#',
  },
  // Job 3
  {
    name: 'Web Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/web-developer',
    submit_URL: '#',
  },
  // Job 4
  {
    name: 'Copywritting',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing & Content Writer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/copywriting',
    submit_URL: '#',
  },
  // Job 5
  {
    name: 'Personal Assistant',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Personal Assistant',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/personal-assistant',
    submit_URL: '#',
  },
  // Job 6
  {
    name: 'Affiliate',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Ads, Affiliate & Social Media',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/affiliate',
    submit_URL: '#',
  },
  // Job 7
  {
    name: 'CRM',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'CRM',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/crm',
    submit_URL: '#',
  },
  // Job 8
  {
    name: 'Purchasing',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Purchasing',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: 'career/purchasing',
    submit_URL: '#',
  },
  // Job 9
  {
    name: 'Grapich Designer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Design & UX',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 10
  {
    name: 'Ads Facebook',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 1
  {
    name: 'Backend Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/finance',
    submit_URL: '#',
  },
  // Job 2
  {
    name: 'Recruiter',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Human Capital & Talent Acquisition',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/human-resource',
    submit_URL: '#',
  },
  // Job 3
  {
    name: 'Front End Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/web-developer',
    submit_URL: '#',
  },
  // Job 4
  {
    name: 'Penulis Artikel',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing & Content Writer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/copywriting',
    submit_URL: '#',
  },
  // Job 5
  {
    name: 'Pemesan Tiket Pesawat',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Personal Assistant',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/personal-assistant',
    submit_URL: '#',
  },
  // Job 6
  {
    name: 'Tukang Email',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Ads, Affiliate & Social Media',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/affiliate',
    submit_URL: '#',
  },
  // Job 7
  {
    name: 'Hobi Ngobrol',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'CRM',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/crm',
    submit_URL: '#',
  },
  // Job 8
  {
    name: 'Tukang Nawar',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Purchasing',
    location: 'PIK, The New Jakarta City',
    availability: 2,
    URL: 'career/purchasing',
    submit_URL: '#',
  },
  // Job 9
  {
    name: 'Lembur sehari hari',
    time: 'Fulltime',
    staff_level: 'Pengganti Kak Ian',
    division: 'Design & UX',
    location: 'Abu Dhabi, UAE',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 10
  {
    name: 'tukang bangunan digital',
    time: 'Fulltime',
    staff_level: 'CEO',
    division: 'Design & UX',
    location: 'California, America',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 1
  {
    name: 'Finance',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Finance',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/finance',
    submit_URL: '#',
  },
  // Job 2
  {
    name: 'Human Resource',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Human Capital & Talent Acquisition',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/human-resource',
    submit_URL: '#',
  },
  // Job 3
  {
    name: 'Web Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/web-developer',
    submit_URL: '#',
  },
  // Job 4
  {
    name: 'Copywritting',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing & Content Writer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/copywriting',
    submit_URL: '#',
  },
  // Job 5
  {
    name: 'Personal Assistant',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Personal Assistant',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/personal-assistant',
    submit_URL: '#',
  },
  // Job 6
  {
    name: 'Affiliate',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Ads, Affiliate & Social Media',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/affiliate',
    submit_URL: '#',
  },
  // Job 7
  {
    name: 'CRM',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'CRM',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/crm',
    submit_URL: '#',
  },
  // Job 8
  {
    name: 'Purchasing',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Purchasing',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: 'career/purchasing',
    submit_URL: '#',
  },
  // Job 9
  {
    name: 'Grapich Designer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Design & UX',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 10
  {
    name: 'Ads Facebook',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 1
  {
    name: 'Backend Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/finance',
    submit_URL: '#',
  },
  // Job 2
  {
    name: 'Recruiter',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Human Capital & Talent Acquisition',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/human-resource',
    submit_URL: '#',
  },
  // Job 3
  {
    name: 'Front End Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/web-developer',
    submit_URL: '#',
  },
  // Job 4
  {
    name: 'Penulis Artikel',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing & Content Writer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/copywriting',
    submit_URL: '#',
  },
  // Job 5
  {
    name: 'Pemesan Tiket Pesawat',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Personal Assistant',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/personal-assistant',
    submit_URL: '#',
  },
  // Job 6
  {
    name: 'Tukang Email',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Ads, Affiliate & Social Media',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/affiliate',
    submit_URL: '#',
  },
  // Job 7
  {
    name: 'Hobi Ngobrol',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'CRM',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/crm',
    submit_URL: '#',
  },
  // Job 8
  {
    name: 'Tukang Nawar',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Purchasing',
    location: 'PIK, The New Jakarta City',
    availability: 2,
    URL: 'career/purchasing',
    submit_URL: '#',
  },
  // Job 9
  {
    name: 'Lembur sehari hari',
    time: 'Fulltime',
    staff_level: 'Pengganti Kak Ian',
    division: 'Design & UX',
    location: 'Abu Dhabi, UAE',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 10
  {
    name: 'tukang bangunan digital',
    time: 'Fulltime',
    staff_level: 'CEO',
    division: 'Design & UX',
    location: 'California, America',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 1
  {
    name: 'Finance',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Finance',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/finance',
    submit_URL: '#',
  },
  // Job 2
  {
    name: 'Human Resource',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Human Capital & Talent Acquisition',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/human-resource',
    submit_URL: '#',
  },
  // Job 3
  {
    name: 'Web Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/web-developer',
    submit_URL: '#',
  },
  // Job 4
  {
    name: 'Copywritting',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing & Content Writer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/copywriting',
    submit_URL: '#',
  },
  // Job 5
  {
    name: 'Personal Assistant',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Personal Assistant',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/personal-assistant',
    submit_URL: '#',
  },
  // Job 6
  {
    name: 'Affiliate',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Ads, Affiliate & Social Media',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/affiliate',
    submit_URL: '#',
  },
  // Job 7
  {
    name: 'CRM',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'CRM',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/crm',
    submit_URL: '#',
  },
  // Job 8
  {
    name: 'Purchasing',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Purchasing',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: 'career/purchasing',
    submit_URL: '#',
  },
  // Job 9
  {
    name: 'Grapich Designer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Design & UX',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 10
  {
    name: 'Ads Facebook',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 1
  {
    name: 'Backend Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/finance',
    submit_URL: '#',
  },
  // Job 2
  {
    name: 'Recruiter',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Human Capital & Talent Acquisition',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/human-resource',
    submit_URL: '#',
  },
  // Job 3
  {
    name: 'Front End Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/web-developer',
    submit_URL: '#',
  },
  // Job 4
  {
    name: 'Penulis Artikel',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing & Content Writer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/copywriting',
    submit_URL: '#',
  },
  // Job 5
  {
    name: 'Pemesan Tiket Pesawat',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Personal Assistant',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/personal-assistant',
    submit_URL: '#',
  },
  // Job 6
  {
    name: 'Tukang Email',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Ads, Affiliate & Social Media',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/affiliate',
    submit_URL: '#',
  },
  // Job 7
  {
    name: 'Hobi Ngobrol',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'CRM',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/crm',
    submit_URL: '#',
  },
  // Job 8
  {
    name: 'Tukang Nawar',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Purchasing',
    location: 'PIK, The New Jakarta City',
    availability: 2,
    URL: 'career/purchasing',
    submit_URL: '#',
  },
  // Job 9
  {
    name: 'Lembur sehari hari',
    time: 'Fulltime',
    staff_level: 'Pengganti Kak Ian',
    division: 'Design & UX',
    location: 'Abu Dhabi, UAE',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 10
  {
    name: 'tukang bangunan digital',
    time: 'Fulltime',
    staff_level: 'CEO',
    division: 'Design & UX',
    location: 'California, America',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 1
  {
    name: 'Finance',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Finance',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/finance',
    submit_URL: '#',
  },
  // Job 2
  {
    name: 'Human Resource',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Human Capital & Talent Acquisition',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/human-resource',
    submit_URL: '#',
  },
  // Job 3
  {
    name: 'Web Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/web-developer',
    submit_URL: '#',
  },
  // Job 4
  {
    name: 'Copywritting',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing & Content Writer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/copywriting',
    submit_URL: '#',
  },
  // Job 5
  {
    name: 'Personal Assistant',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Personal Assistant',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/personal-assistant',
    submit_URL: '#',
  },
  // Job 6
  {
    name: 'Affiliate',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Ads, Affiliate & Social Media',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/affiliate',
    submit_URL: '#',
  },
  // Job 7
  {
    name: 'CRM',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'CRM',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/crm',
    submit_URL: '#',
  },
  // Job 8
  {
    name: 'Purchasing',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Purchasing',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: 'career/purchasing',
    submit_URL: '#',
  },
  // Job 9
  {
    name: 'Grapich Designer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Design & UX',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 10
  {
    name: 'Ads Facebook',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 1
  {
    name: 'Backend Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/finance',
    submit_URL: '#',
  },
  // Job 2
  {
    name: 'Recruiter',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Human Capital & Talent Acquisition',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/human-resource',
    submit_URL: '#',
  },
  // Job 3
  {
    name: 'Front End Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/web-developer',
    submit_URL: '#',
  },
  // Job 4
  {
    name: 'Penulis Artikel',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing & Content Writer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/copywriting',
    submit_URL: '#',
  },
  // Job 5
  {
    name: 'Pemesan Tiket Pesawat',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Personal Assistant',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/personal-assistant',
    submit_URL: '#',
  },
  // Job 6
  {
    name: 'Tukang Email',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Ads, Affiliate & Social Media',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/affiliate',
    submit_URL: '#',
  },
  // Job 7
  {
    name: 'Hobi Ngobrol',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'CRM',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/crm',
    submit_URL: '#',
  },
  // Job 8
  {
    name: 'Tukang Nawar',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Purchasing',
    location: 'PIK, The New Jakarta City',
    availability: 2,
    URL: 'career/purchasing',
    submit_URL: '#',
  },
  // Job 9
  {
    name: 'Lembur sehari hari',
    time: 'Fulltime',
    staff_level: 'Pengganti Kak Ian',
    division: 'Design & UX',
    location: 'Abu Dhabi, UAE',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 10
  {
    name: 'tukang bangunan digital',
    time: 'Fulltime',
    staff_level: 'CEO',
    division: 'Design & UX',
    location: 'California, America',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 1
  {
    name: 'Finance',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Finance',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/finance',
    submit_URL: '#',
  },
  // Job 2
  {
    name: 'Human Resource',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Human Capital & Talent Acquisition',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/human-resource',
    submit_URL: '#',
  },
  // Job 3
  {
    name: 'Web Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/web-developer',
    submit_URL: '#',
  },
  // Job 4
  {
    name: 'Copywritting',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing & Content Writer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/copywriting',
    submit_URL: '#',
  },
  // Job 5
  {
    name: 'Personal Assistant',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Personal Assistant',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/personal-assistant',
    submit_URL: '#',
  },
  // Job 6
  {
    name: 'Affiliate',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Ads, Affiliate & Social Media',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/affiliate',
    submit_URL: '#',
  },
  // Job 7
  {
    name: 'CRM',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'CRM',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/crm',
    submit_URL: '#',
  },
  // Job 8
  {
    name: 'Purchasing',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Purchasing',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: 'career/purchasing',
    submit_URL: '#',
  },
  // Job 9
  {
    name: 'Grapich Designer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Design & UX',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 10
  {
    name: 'Ads Facebook',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 1
  {
    name: 'Backend Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/finance',
    submit_URL: '#',
  },
  // Job 2
  {
    name: 'Recruiter',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Human Capital & Talent Acquisition',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/human-resource',
    submit_URL: '#',
  },
  // Job 3
  {
    name: 'Front End Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/web-developer',
    submit_URL: '#',
  },
  // Job 4
  {
    name: 'Penulis Artikel',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing & Content Writer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/copywriting',
    submit_URL: '#',
  },
  // Job 5
  {
    name: 'Pemesan Tiket Pesawat',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Personal Assistant',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/personal-assistant',
    submit_URL: '#',
  },
  // Job 6
  {
    name: 'Tukang Email',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Ads, Affiliate & Social Media',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/affiliate',
    submit_URL: '#',
  },
  // Job 7
  {
    name: 'Hobi Ngobrol',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'CRM',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/crm',
    submit_URL: '#',
  },
  // Job 8
  {
    name: 'Tukang Nawar',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Purchasing',
    location: 'PIK, The New Jakarta City',
    availability: 2,
    URL: 'career/purchasing',
    submit_URL: '#',
  },
  // Job 9
  {
    name: 'Lembur sehari hari',
    time: 'Fulltime',
    staff_level: 'Pengganti Kak Ian',
    division: 'Design & UX',
    location: 'Abu Dhabi, UAE',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 10
  {
    name: 'tukang bangunan digital',
    time: 'Fulltime',
    staff_level: 'CEO',
    division: 'Design & UX',
    location: 'California, America',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 1
  {
    name: 'Finance',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Finance',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/finance',
    submit_URL: '#',
  },
  // Job 2
  {
    name: 'Human Resource',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Human Capital & Talent Acquisition',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/human-resource',
    submit_URL: '#',
  },
  // Job 3
  {
    name: 'Web Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/web-developer',
    submit_URL: '#',
  },
  // Job 4
  {
    name: 'Copywritting',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing & Content Writer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/copywriting',
    submit_URL: '#',
  },
  // Job 5
  {
    name: 'Personal Assistant',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Personal Assistant',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/personal-assistant',
    submit_URL: '#',
  },
  // Job 6
  {
    name: 'Affiliate',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Ads, Affiliate & Social Media',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/affiliate',
    submit_URL: '#',
  },
  // Job 7
  {
    name: 'CRM',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'CRM',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/crm',
    submit_URL: '#',
  },
  // Job 8
  {
    name: 'Purchasing',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Purchasing',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: 'career/purchasing',
    submit_URL: '#',
  },
  // Job 9
  {
    name: 'Grapich Designer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Design & UX',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 10
  {
    name: 'Ads Facebook',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 1
  {
    name: 'Backend Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/finance',
    submit_URL: '#',
  },
  // Job 2
  {
    name: 'Recruiter',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Human Capital & Talent Acquisition',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/human-resource',
    submit_URL: '#',
  },
  // Job 3
  {
    name: 'Front End Developer',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Full Stack Web Developer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/web-developer',
    submit_URL: '#',
  },
  // Job 4
  {
    name: 'Penulis Artikel',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Marketing & Content Writer',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/copywriting',
    submit_URL: '#',
  },
  // Job 5
  {
    name: 'Pemesan Tiket Pesawat',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Personal Assistant',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/personal-assistant',
    submit_URL: '#',
  },
  // Job 6
  {
    name: 'Tukang Email',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Ads, Affiliate & Social Media',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/affiliate',
    submit_URL: '#',
  },
  // Job 7
  {
    name: 'Hobi Ngobrol',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'CRM',
    location: 'Jakarta, Indonesia',
    availability: 2,
    URL: '/career/crm',
    submit_URL: '#',
  },
  // Job 8
  {
    name: 'Tukang Nawar',
    time: 'Fulltime',
    staff_level: 'Staff Level',
    division: 'Purchasing',
    location: 'PIK, The New Jakarta City',
    availability: 2,
    URL: 'career/purchasing',
    submit_URL: '#',
  },
  // Job 9
  {
    name: 'Lembur sehari hari',
    time: 'Fulltime',
    staff_level: 'Pengganti Kak Ian',
    division: 'Design & UX',
    location: 'Abu Dhabi, UAE',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Job 10
  {
    name: 'tukang bangunan digital',
    time: 'Fulltime',
    staff_level: 'CEO',
    division: 'Design & UX',
    location: 'California, America',
    availability: 2,
    URL: '/career/graphic-designer',
    submit_URL: '#',
  },
  // Add more job objects as needed
];

export default jobs;
